name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Ubuntu_18_04:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install requirements
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install python3 libpng++-dev zlib1g-dev g++-8 libboost-program-options-dev wget lcov libjson-perl libperlio-gzip-perl
        # LCOV 1.13 has some issues with parsing gcc 8+ gcda files
        wget http://archive.ubuntu.com/ubuntu/pool/universe/l/lcov/lcov_1.14-2_all.deb
        sudo dpkg -i lcov_1.14-2_all.deb 
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
        sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-8 90
        g++ --version
        gcov --version
    
    - name: Patch libraries
      run: |
        git apply -p0 patches/leveldb-1.22.patch
        git apply -p0 patches/pugixml-disable-install.patch

    - name: Build
      run: |
        mkdir build && cd build
        export CC=/usr/bin/gcc-8
        export CXX=/usr/bin/g++-8
        cmake -DBUILD_TESTS=ON -DCODE_COVERAGE=ON ..
        make

    - name: Test (PR)
      if: github.event_name == 'pull_request'
      run: |
        ./build/bedrock-viz-test --gtest_output="xml:unittests.xml" --gtest_filter="Unit*:*.Unit*"
        ./build/bedrock-viz-test --gtest_output="xml:integrationtests.xml" --gtest_filter="Integration*:*.Integration*"
        ./build/bedrock-viz-test --gtest_output="xml:ungroupedtests.xml" --gtest_filter="-Unit*:*.Unit*:Integration*:*.Integration*"

    - name: Test
      if: github.event_name != 'pull_request'
      continue-on-error: true
      run: |
        ./build/bedrock-viz-test --gtest_output="xml:unittests.xml" --gtest_filter="Unit*:*.Unit*"
        ./build/bedrock-viz-test --gtest_output="xml:integrationtests.xml" --gtest_filter="Integration*:*.Integration*"
        ./build/bedrock-viz-test --gtest_output="xml:ungroupedtests.xml" --gtest_filter="-Unit*:*.Unit*:Integration*:*.Integration*"

    - name: Upload Test Report
      if: github.event_name != 'pull_request'
      env:
        REPORT_CI_TOKEN: ${{secrets.REPORT_CI_TOKEN}}
      run: | 
        curl -s https://report.ci/upload.py | python3 - --include='*.xml' --framework=gtest 
    
    - name: Generate Coverage Report
      run: | 
        lcov --base-directory . --directory build -c -o coverage.info
        lcov --remove coverage.info '/usr/*' '*/third_party/*' '*/tests/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with: 
        file: coverage.info

  macOS_10_15:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install requirements
      run: |
        brew install libpng
        brew install boost
    
    - name: Patch libraries
      run: |
        git apply -p0 patches/leveldb-1.22.patch
        git apply -p0 patches/pugixml-disable-install.patch

    - name: Build
      run: |
        mkdir build && cd build
        cmake ..
        make
  
  Windows:
    runs-on: windows-latest

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Install requirements
      run: |
        vcpkg install zlib:x64-windows libpng:x64-windows boost-program-options:x64-windows
    
    - name: Patch libraries
      run: |
        git apply -p0 patches/leveldb-1.22.patch
        git apply -p0 patches/pugixml-disable-install.patch
    
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 16 2019" -A x64
        msbuild bedrock-viz.sln
